# author ming
# 构建 jiuming-tools 推送到pypi上
# 基于 github actions 监听 tag  根据tag 构建发布 到pypi
# 环境变量    PYPI_USERNAME PYPI_PASSWORD
# 参考文档: https://github.com/actions/starter-workflows/blob/main/ci/python-publish.yml
on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: install
        run: |
          python -m pip install --upgrade pip
          pip -V
          python -V
          pip install pipenv twine
          pipenv install
      - name: updateVersion
        #global_config.py中 version的值+1
        run: |

      - name: build
        # 构建
        run: |
          pipenv run python setup.py sdist bdist_wheel
      - name: pushToPypi
        env:
          #twine 账户密码
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        #推送
        run: |
          twine upload dist/*